/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ScheduleStructure;

import java.awt.Color;
import javax.swing.UIManager;

/**
 *
 * @author angelponce
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        groupThemes = new javax.swing.ButtonGroup();
        container = new javax.swing.JPanel();
        hoursPanel = new javax.swing.JPanel();
        daysPanel = new javax.swing.JPanel();
        mondayLabel = new javax.swing.JLabel();
        tuesdayLabel = new javax.swing.JLabel();
        wednesdayLabel = new javax.swing.JLabel();
        thursdayLabel = new javax.swing.JLabel();
        fridayLabel = new javax.swing.JLabel();
        centerPanel = new javax.swing.JPanel();
        crossPanel = new javax.swing.JPanel();
        hourLabel = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        configMenu = new javax.swing.JMenu();
        addRowOption = new javax.swing.JMenuItem();
        separator1 = new javax.swing.JPopupMenu.Separator();
        createSchedule = new javax.swing.JMenuItem();
        separator2 = new javax.swing.JPopupMenu.Separator();
        reestartOption = new javax.swing.JMenuItem();
        separator3 = new javax.swing.JPopupMenu.Separator();
        themeOptions = new javax.swing.JMenu();
        lightTheme = new javax.swing.JRadioButtonMenuItem();
        lightBlueTheme = new javax.swing.JRadioButtonMenuItem();
        blueGrayTheme = new javax.swing.JRadioButtonMenuItem();
        grayTheme = new javax.swing.JRadioButtonMenuItem();
        orangeTheme = new javax.swing.JRadioButtonMenuItem();
        pinkTheme = new javax.swing.JRadioButtonMenuItem();
        purpleTheme = new javax.swing.JRadioButtonMenuItem();
        darkTheme = new javax.swing.JRadioButtonMenuItem();
        separator4 = new javax.swing.JPopupMenu.Separator();
        exitOption = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 540));

        container.setForeground(new java.awt.Color(255, 255, 255));
        container.setPreferredSize(new java.awt.Dimension(1200, 440));
        container.setLayout(new java.awt.GridBagLayout());

        hoursPanel.setBackground(new java.awt.Color(204, 255, 204));
        hoursPanel.setMinimumSize(new java.awt.Dimension(200, 400));
        hoursPanel.setPreferredSize(new java.awt.Dimension(200, 400));
        hoursPanel.setLayout(new java.awt.GridLayout(1, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        container.add(hoursPanel, gridBagConstraints);

        daysPanel.setBackground(new java.awt.Color(255, 204, 204));
        daysPanel.setMinimumSize(new java.awt.Dimension(1000, 40));
        daysPanel.setPreferredSize(new java.awt.Dimension(1000, 40));
        daysPanel.setLayout(new java.awt.GridLayout(1, 5));

        mondayLabel.setFont(new java.awt.Font("Verdana", 1, 15)); // NOI18N
        mondayLabel.setForeground(new java.awt.Color(0, 0, 0));
        mondayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mondayLabel.setText("Lunes");
        daysPanel.add(mondayLabel);

        tuesdayLabel.setFont(new java.awt.Font("Verdana", 1, 15)); // NOI18N
        tuesdayLabel.setForeground(new java.awt.Color(0, 0, 0));
        tuesdayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tuesdayLabel.setText("Martes");
        daysPanel.add(tuesdayLabel);

        wednesdayLabel.setFont(new java.awt.Font("Verdana", 1, 15)); // NOI18N
        wednesdayLabel.setForeground(new java.awt.Color(0, 0, 0));
        wednesdayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wednesdayLabel.setText("Miércoles");
        daysPanel.add(wednesdayLabel);

        thursdayLabel.setFont(new java.awt.Font("Verdana", 1, 15)); // NOI18N
        thursdayLabel.setForeground(new java.awt.Color(0, 0, 0));
        thursdayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        thursdayLabel.setText("Jueves");
        daysPanel.add(thursdayLabel);

        fridayLabel.setFont(new java.awt.Font("Verdana", 1, 15)); // NOI18N
        fridayLabel.setForeground(new java.awt.Color(0, 0, 0));
        fridayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fridayLabel.setText("Viernes");
        daysPanel.add(fridayLabel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        container.add(daysPanel, gridBagConstraints);

        centerPanel.setBackground(new java.awt.Color(153, 153, 255));
        centerPanel.setMinimumSize(new java.awt.Dimension(1000, 400));
        centerPanel.setPreferredSize(new java.awt.Dimension(1000, 400));
        centerPanel.setLayout(new java.awt.GridLayout(1, 5));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        container.add(centerPanel, gridBagConstraints);

        crossPanel.setBackground(new java.awt.Color(204, 255, 255));
        crossPanel.setPreferredSize(new java.awt.Dimension(200, 40));
        crossPanel.setLayout(new java.awt.GridLayout(1, 0));

        hourLabel.setFont(new java.awt.Font("Verdana", 1, 15)); // NOI18N
        hourLabel.setForeground(new java.awt.Color(0, 0, 0));
        hourLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hourLabel.setText("HORA");
        crossPanel.add(hourLabel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        container.add(crossPanel, gridBagConstraints);

        getContentPane().add(container, java.awt.BorderLayout.CENTER);

        configMenu.setForeground(new java.awt.Color(0, 0, 0));
        configMenu.setText("Configuración");

        addRowOption.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        addRowOption.setText("Agregar fila");
        configMenu.add(addRowOption);
        configMenu.add(separator1);

        createSchedule.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/create.png"))); // NOI18N
        createSchedule.setText("Crear horario");
        configMenu.add(createSchedule);
        configMenu.add(separator2);

        reestartOption.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reestart.png"))); // NOI18N
        reestartOption.setText("Reiniciar horario");
        configMenu.add(reestartOption);
        configMenu.add(separator3);

        themeOptions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/theme.png"))); // NOI18N
        themeOptions.setText("Cambiar tema");

        lightTheme.setSelected(true);
        lightTheme.setText("Claro");
        lightTheme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/light.jpeg"))); // NOI18N
        themeOptions.add(lightTheme);

        lightBlueTheme.setText("Azul-Claro");
        lightBlueTheme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/light-blue.jpeg"))); // NOI18N
        lightBlueTheme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lightBlueThemeActionPerformed(evt);
            }
        });
        themeOptions.add(lightBlueTheme);

        blueGrayTheme.setText("Gris-Azulado");
        blueGrayTheme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/blue-gray.jpeg"))); // NOI18N
        themeOptions.add(blueGrayTheme);

        grayTheme.setText("Gris");
        grayTheme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gray.jpeg"))); // NOI18N
        themeOptions.add(grayTheme);

        orangeTheme.setText("Naranja");
        orangeTheme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/orange.jpeg"))); // NOI18N
        themeOptions.add(orangeTheme);

        pinkTheme.setText("Rosa");
        pinkTheme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pink.jpeg"))); // NOI18N
        pinkTheme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinkThemeActionPerformed(evt);
            }
        });
        themeOptions.add(pinkTheme);

        purpleTheme.setText("Violeta");
        purpleTheme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/purple.jpeg"))); // NOI18N
        themeOptions.add(purpleTheme);

        darkTheme.setText("Oscuro");
        darkTheme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dark.jpeg"))); // NOI18N
        darkTheme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                darkThemeActionPerformed(evt);
            }
        });
        themeOptions.add(darkTheme);

        configMenu.add(themeOptions);
        configMenu.add(separator4);

        exitOption.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exit.png"))); // NOI18N
        exitOption.setText("Salir");
        configMenu.add(exitOption);

        menuBar.add(configMenu);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pinkThemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinkThemeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pinkThemeActionPerformed

    private void darkThemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_darkThemeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_darkThemeActionPerformed

    private void lightBlueThemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lightBlueThemeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lightBlueThemeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem addRowOption;
    public javax.swing.JRadioButtonMenuItem blueGrayTheme;
    public javax.swing.JPanel centerPanel;
    public javax.swing.JMenu configMenu;
    public javax.swing.JPanel container;
    public javax.swing.JMenuItem createSchedule;
    public javax.swing.JPanel crossPanel;
    public javax.swing.JRadioButtonMenuItem darkTheme;
    public javax.swing.JPanel daysPanel;
    public javax.swing.JMenuItem exitOption;
    public javax.swing.JLabel fridayLabel;
    public javax.swing.JRadioButtonMenuItem grayTheme;
    public javax.swing.ButtonGroup groupThemes;
    public javax.swing.JLabel hourLabel;
    public javax.swing.JPanel hoursPanel;
    public javax.swing.JRadioButtonMenuItem lightBlueTheme;
    public javax.swing.JRadioButtonMenuItem lightTheme;
    public javax.swing.JMenuBar menuBar;
    public javax.swing.JLabel mondayLabel;
    public javax.swing.JRadioButtonMenuItem orangeTheme;
    public javax.swing.JRadioButtonMenuItem pinkTheme;
    public javax.swing.JRadioButtonMenuItem purpleTheme;
    public javax.swing.JMenuItem reestartOption;
    private javax.swing.JPopupMenu.Separator separator1;
    public javax.swing.JPopupMenu.Separator separator2;
    public javax.swing.JPopupMenu.Separator separator3;
    public javax.swing.JPopupMenu.Separator separator4;
    public javax.swing.JMenu themeOptions;
    public javax.swing.JLabel thursdayLabel;
    public javax.swing.JLabel tuesdayLabel;
    public javax.swing.JLabel wednesdayLabel;
    // End of variables declaration//GEN-END:variables
}
